### ISSUE TITLE
editcalendarresource: only 2 packages for a calendar ressource

### ISSUE THREAD

**Issue by AUBMA** [bgo-bioimagerie/sygrrif#15]
Il est possible sur la page web de saisir plein de packages (en cliquant sur le bouton ajouter) mais seuls deux s'insèrent en base.

Exemple :
On a deux package en base (package 1 et package 2)
On en ajoute deux via la page editcalendarresource (package 3 et package 4)
On trouve en base (table sy_packages) : package 4 (qui écrase package 1) et package 2 (le package 3 n'est pas retenu).

**Comment by bgo-bioimagerie** [comment]
le dernier commit du master corrige ce bug
