### ISSUE TITLE
Statistiques : Utilisateurs ayant réservé

### ISSUE THREAD

**Issue by AUBMA** [bgo-bioimagerie/sygrrif#34]
https://gehsyg.univ-rennes1.fr/sygrrifstats/statbookingusers

Notice: Undefined offset: 2 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 671 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 1 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 671 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 1 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 672 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 2 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 672 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: A non well formed numeric value encountered in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 672 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 0.0237 6837040 7. mktime() /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php:672 Notice: Undefined offset: 2 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 676 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 1 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 676 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 1 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 677 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: Undefined offset: 2 in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 677 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 Notice: A non well formed numeric value encountered in /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php on line 677 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0232 6836288 6. SyStatsUser->bookingUsers() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:495 0.0243 6837568 7. mktime() /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php:677 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php:676) in /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php on line 518 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0426 6889656 6. ControllerSygrrifstats->exportstatbookingusersCSV() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:497 0.0426 6889824 7. header() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:518 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/sygrrif_prod/Modules/sygrrif/Model/SyStatsUser.php:676) in /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php on line 519 Call Stack: 0.0001 671760 1. {main}() /var/www/html/sygrrif_prod/index.php:0 0.0013 803848 2. router->routerRequest() /var/www/html/sygrrif_prod/index.php:9 0.0216 6825320 3. ControllerSecure->runAction() /var/www/html/sygrrif_prod/Framework/Router.php:26 0.0230 6826744 4. Controller->runAction() /var/www/html/sygrrif_prod/Modules/core/Controller/ControllerSecure.php:40 0.0230 6826744 5. ControllerSygrrifstats->statbookingusers() /var/www/html/sygrrif_prod/Framework/Controller.php:42 0.0426 6889656 6. ControllerSygrrifstats->exportstatbookingusersCSV() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:497 0.0429 6889816 7. header() /var/www/html/sygrrif_prod/Modules/sygrrif/Controller/ControllerSygrrifstats.php:519 name ; email Hémon July;july.hemon@univ-rennes1.fr admin administrateur;bioinfo-gensante@univ-rennes1.fr;eve.hellequin@gmail.com

**Comment by bgo-bioimagerie** [comment]
corrigé dans le commit b97e3146269a44438805bee3a99c657a6668a157
